# Example - Complex
#
# Agent running with a more complex configuration

FROM datadog/docker-dd-agent

# Add Apache check configuration
ADD datadog.conf /etc/dd-agent/datadog.conf
ADD network.yaml /etc/dd-agent/conf.d/network.yaml
