#!/bin/bash
set -ex

AGENT_VERSION=1:5.27.1-1
AGENT_REPO="https://apt.datadoghq.com/"
AGENT_REPO_CHANNEL=stable

docker build \
        --build-arg AGENT_VERSION_ARG=${AGENT_VERSION} \
        --build-arg AGENT_REPO_ARG=${AGENT_REPO} \
        --build-arg AGENT_REPO_CHANNEL_ARG=${AGENT_REPO_CHANNEL} \
        --tag "${DOCKER_REPO}:${DOCKER_TAG}" \
        .
