#!/bin/bash
set -ex

AGENT_VERSION=1:5.28.99-dockertest.rc.1-1
AGENT_REPO=http://apt.datad0g.com/
AGENT_REPO_CHANNEL=beta

docker build \
        --build-arg AGENT_VERSION_ARG=${AGENT_VERSION} \
        --build-arg AGENT_REPO_ARG=${AGENT_REPO} \
        --build-arg AGENT_REPO_CHANNEL_ARG=${AGENT_REPO_CHANNEL} \
        --tag "${DOCKER_REPO}:${DOCKER_TAG}" \
        .
